name: "Multi event pipeline"

on:
    push:
        branches:
            - main
            - test
        



jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main branch"
              run: echo "Running on main branch"
