name: "Multi event pipeline"

on:
    push: #event
        branches:
            - main
            - test
    pull_request: #event
        branches:
            - main
            - test
        types:
            - closed
            - opened

    workflow_dispatch:

        

jobs:
    on-push: #job1 name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main branch"
              run: echo "Running on main branch"

    on-pull-request: #job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "pulling on main branch"
              run: echo "pulling from main branch"
    
    on-workflow_dispatch: #job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "running on wrkflow dispatch"
              run: echo "running on wrkflow dispatch"
    
    on-pull-request-closed: #job 4
        if: github.event_name == 'pull_request' && github.event.action=='closed'
        runs-on: ubuntu-latest
        steps:
            - name: "running on pull request closed"
              run: echo "running on pull request cloded"
    
    on-pull-request-opened: #job 4
        if: github.event_name == 'pull_request' && github.event.action=='opened'
        runs-on: ubuntu-latest
        steps:
            - name: "running on pull request opened"
              run: echo "running on pull request opened"